### ISSUE TITLE
Mu compatibility 

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambd_micropython#10]
![image](https://user-images.githubusercontent.com/663460/131263411-62433651-d3ba-4b72-bc7a-57e143904669.png)

Mu is a Python code editor for beginner programmers based on extensive feedback given by teachers and learners.

Reference:

https://codewith.mu/en/

**Comment by xidameng** [comment]
Hi Thanks for the suggestion, we will add support for Thonny IDE in the near future
