### ISSUE TITLE
Merge Ameba Port to Upstream

### ISSUE THREAD

**Issue by xidameng** [ambiot/ambd_micropython#18]
# Task List
This task list is to track TO-DO and monitor the progress for works to be done before the final merge of Ameba port to MicroPython upstream

## Build System
- [x] #20
- [x] #21
- [x] #22
- [x] #19

## API Re-design
- [x] #23
- [x] SPI
- [x] I2C
- [x] PWM
- [x] ADC
- [x] Pin
- [x] Timer
- [x] RTC
- [x] UART

## Feature Request
- [x] #24

## Tools Support 
- [x] #25

**Comment by 5t0n3r1pp3r** [comment]
how can i help? @xidameng

**Comment by simplexion-blechschmidt** [comment]
Are there currently plans to also port the [BLE part](https://github.com/ambiot/ambd_sdk/tree/dev/component/common/bluetooth/realtek/sdk) of the SDK?

**Comment by M-ichae-l** [comment]
> 

Thanks @5t0n3r1pp3r , for this issue all tasks are done. No further help required.

**Comment by M-ichae-l** [comment]
> 

@simplexion-blechschmidt  currently the SDK has no BLE. It will coming in future after the SDK merged into official micropython SDK.

**Comment by M-ichae-l** [comment]
Closed as there is no further tasks.
