### ISSUE TITLE
Support for BW16 module dev board (RTL8720DN)

### ISSUE THREAD

**Issue by happyme531** [ambiot/ambd_micropython#2]
There is a low-cost dev board of RTL8720DN available. It only costs $5. 
The RTL8720DN have the same processor, memory and wireless support as the RTL8722, but with lesser GPIO. 

When I flashed the image built for RTL8722 into it, it only shows
```
#calibration_ok:[2:19:11]
```
and no more.

Since arduino for RTL8722 can run on RTL8720 with some little modifications (like pin definition), I think this is also possible. 

Details about the module can be found here: [link](https://docs.ai-thinker.com/en/rtl87xx)

**Comment by xidameng** [comment]
Where do you buy it from?  Only RTL8720 module sells for less than$5, dev board is alot more costly than this. 
Plus, RTL8720 is not the official supported model for this MicroPython port, porting to RTL8720DN will have to rely on the community

**Comment by happyme531** [comment]
> Where do you buy it from? Only RTL8720 module sells for less than$5, dev board is alot more costly than this.
> Plus, RTL8720 is not the official supported model for this MicroPython port, porting to RTL8720DN will have to rely on the community

I got it on TaoBao. The module is also selled at 3.5$ for each. Really cheap, right?
link: https://item.taobao.com/item.htm?&id=610183312653

The real problem is the documentation is so poor. There are only some headers and some examples available.

**Comment by xidameng** [comment]
> > Where do you buy it from? Only RTL8720 module sells for less than$5, dev board is alot more costly than this.
> > Plus, RTL8720 is not the official supported model for this MicroPython port, porting to RTL8720DN will have to rely on the community
> 
> I got it on TaoBao. The module is also selled at 3.5$ for each. Really cheap, right?
> link: https://item.taobao.com/item.htm?&id=610183312653
> 
> The real problem is the documentation is so poor. There are only some headers and some examples available.

Ok, really good buy👍🏻
I can't say for sure, but just an hypothesis-- MicroPython require a lot more ram than normal C firmware, thus using the on-board PSRAM is necessary. The official supported model RTL8722 comes with 4MB PSRAM, if RTL8720 has 4MB PSRAM then there is a chance MicroPython can run.

btw, I dont know what kind of document Taobao gives to you, but Seeed studio also sells this model and they have documents ready for download to everyone

**Comment by happyme531** [comment]
> > > Where do you buy it from? Only RTL8720 module sells for less than$5, dev board is alot more costly than this.
> > > Plus, RTL8720 is not the official supported model for this MicroPython port, porting to RTL8720DN will have to rely on the community
> > 
> > 
> > I got it on TaoBao. The module is also selled at 3.5$ for each. Really cheap, right?
> > link: https://item.taobao.com/item.htm?&id=610183312653
> > The real problem is the documentation is so poor. There are only some headers and some examples available.
> 
> Ok, really good buy👍🏻
> I can't say for sure, but just an hypothesis-- MicroPython require a lot more ram than normal C firmware, thus using the on-board PSRAM is necessary. The official supported model RTL8722 comes with 4MB PSRAM, if RTL8720 has 4MB PSRAM then there is a chance MicroPython can run.
> 
> btw, I dont know what kind of document Taobao gives to you, but Seeed studio also sells this model and they have documents ready for download to everyone

The rtl872x have ~512KB SRAM available to m4 core. That is already a lot of RAM! The micropython can runs well even on esp8266(160KB SRAM), so I think memory is not the problem.
Also, from the build log, the psram have a size of 0, probably means unused.

**Comment by xidameng** [comment]
> > Where do you buy it from? Only RTL8720 module sells for less than$5, dev board is alot more costly than this.
> > Plus, RTL8720 is not the official supported model for this MicroPython port, porting to RTL8720DN will have to rely on the community
> 
> I got it on TaoBao. The module is also selled at 3.5$ for each. Really cheap, right?
> link: https://item.taobao.com/item.htm?&id=610183312653
> 
> The real problem is the documentation is so poor. There are only some headers and some examples available.

Search www.amebaiot.com

This is the official website, there are a lot of resource there, also check out forum.amebaiot.com for community support

**Comment by xidameng** [comment]
WiFi and BT stack easily takes up a lot of space, esp8266 only worries wifi...
 honestly, 500KB ram is not that big, if you would look at the linker script you will see many data are allocated on the PSRAM section thus, without it Micropython wont work
