### ISSUE TITLE
Error occured while mounting file system

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambd_micropython#7]
```console
#calibration_ok:[2:19:11]
FATFS Register: disk driver 0
FATFS mount logical drive fail:3
[DRIVER]: Error occured while mounting file system

[MP]: Imported all builtin libraries

MicroPython RTL8722 V1.0.1 by Realtek Ameba; Commit: b400724-dirty on 2021-07-13
Type "help()" for more information.

```

**Comment by xidameng** [comment]
> ```
> #calibration_ok:[2:19:11]
> FATFS Register: disk driver 0
> FATFS mount logical drive fail:3
> [DRIVER]: Error occured while mounting file system
> 
> [MP]: Imported all builtin libraries
> 
> MicroPython RTL8722 V1.0.1 by Realtek Ameba; Commit: b400724-dirty on 2021-07-13
> Type "help()" for more information.
> ```

Hi this has been fixed in the `dev` branch, you may use this link to update the firmware:
https://github.com/ambiot/ambd_micropython/tree/dev/Release

**Comment by xidameng** [comment]
Hi @ajsb85 

Please be reminded that up to now, the SD card filesystem is designed for RTL8722_mini board which comes with SD card slot out of the box, for it to work with RTL8722 (bigger board), there will be some changes to the pin connection

**Comment by ajsb85** [comment]
![image](https://user-images.githubusercontent.com/663460/130719901-1d5f8b88-cdc4-498f-ac5d-116e3d269960.png)


```console
#calibration_ok:[2:19:11]

[MP]: Imported all builtin libraries

MicroPython RTL8722 V1.0.1 by Realtek Ameba; Commit: a925e7c on 2021-07-22
Type "help()" for more information.
>>>


```

**Comment by ajsb85** [comment]
Hi, @xidameng 

Could you provide information to add the SD to the big board?

**Comment by xidameng** [comment]
> Hi, @xidameng
> 
> Could you provide information to add the SD to the big board?

SD card is already supported on Arduino @ https://github.com/ambiot/ambd_arduino/tree/master/Arduino_package/hardware/libraries/FatfsSDIO
